"""empty message

Revision ID: 136dd8c0fa83
Revises: 
Create Date: 2023-01-19 14:57:18.035840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136dd8c0fa83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('string')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('string', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('updatted_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('number')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
